version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - data:/Stuff/Soft/postgreSQL/data/base/49694
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
